/**
 * @file figure.cpp
 * @brief Implementation of the Figure base class methods.
 */
#include "figure.h"

#include <fstream>
#include <iostream>
#include <vector>
#include <map>
#include <cmath>

using namespace std;

/**
 * @struct VertexCompare
 * @brief A comparator for Vertex objects used to filter duplicates in a map.
 */
struct VertexCompare {
    /**
     * @brief Compares two vertices considering a small epsilon value.
     * @param a The first Vertex.
     * @param b The second Vertex.
     * @return true if vertex 'a' is strictly less than vertex 'b'.
     */
    bool operator()(const Vertex& a, const Vertex& b) const {
        const float EPSILON = 1e-5f;
        
        // compare positions
        if (abs(a.x - b.x) > EPSILON) return a.x < b.x;
        if (abs(a.y - b.y) > EPSILON) return a.y < b.y;
        if (abs(a.z - b.z) > EPSILON) return a.z < b.z;
        
        // compare normals
        if (abs(a.nx - b.nx) > EPSILON) return a.nx < b.nx;
        if (abs(a.ny - b.ny) > EPSILON) return a.ny < b.ny;
        if (abs(a.nz - b.nz) > EPSILON) return a.nz < b.nz;

        // compare texture coordinates
        if (abs(a.tu - b.tu) > EPSILON) return a.tu < b.tu;
        if (abs(a.tv - b.tv) > EPSILON) return a.tv < b.tv;
        
        return false;
    }
};

/**
 * @brief Writes the generated vertices to a file using a legacy format.
 * @param filename The path and name of the file to write to.
 */
void Figure::writeToFileLegacy(const string& filename) {
    vector<Vertex> vertices = this->generate();

    ofstream file(filename);

    if (!file.is_open()) {
        cerr << "Error: Could not open file " << filename << "\n";
        return;
    }

    file << "# Generated by CG-2526 Generator (linear)\n";

    file << vertices.size() << "\n";

    for (auto& v : vertices) {
        file << v.x << " " << v.y << " " << v.z << "\n";
    }

    file.close();

    cout << "Successfully generated " << filename << " with " << vertices.size() << " vertices.\n";
}

/**
 * @brief Writes the generated vertices to a file using the standard .obj-like format.
 * @param filename The path and name of the file to write to.
 */
void Figure::writeToFile(const string& filename) {
    vector<Vertex> vertices = this->generate();

    ofstream file(filename);

    if (!file.is_open()) {
        cerr << "Error: Could not open file " << filename << "\n";
        return;
    }

    file << "# Generated by CG-2526 Generator (waveformat)\n";

    map<Vertex, int, VertexCompare> vertexMap;
    int currentId = 1;

    for (const auto& v : vertices) {
        if (vertexMap.find(v) == vertexMap.end()) {
            vertexMap[v] = currentId++;
            file << "v " << v.x << " " << v.y << " " << v.z << " " 
                 << v.nx << " " << v.ny << " " << v.nz << " "
                 << v.tu << " " << v.tv << "\n";
        }
    }

    file << "\n";

    for (size_t i = 0; i < vertices.size(); i += 3) {
        int id1 = vertexMap[vertices[i]];
        int id2 = vertexMap[vertices[i + 1]];
        int id3 = vertexMap[vertices[i + 2]];
        
        file << "f " << id1 << " " << id2 << " " << id3 << "\n";
    }

    file.close();

    cout << "Successfully generated " << filename << "\n";
    cout << "  - Original vertices: " << vertices.size() << "\n";
    cout << "  - Unique vertices:   " << vertexMap.size() << "\n";
    cout << "  - Triangles:         " << vertices.size() / 3 << "\n";
}
